### PR TITLE
iPhone changes done

### PR DESCRIPTION
**Pull request by varun-naharia**

### CODE REVIEW

**Comment by jumartin** [comment]
That's great, thanks!

**Comment by varun-naharia** [comment]
when will you merge them ?

**Comment by jumartin** [comment]
It's all merged already! In branch iPhone-compatibility, the commit before the last one. I don't want to merge in master yet, since a few things need to be fixed still. Thanks for your work!

**Comment by varun-naharia** [comment]
what are the more few changes that needs to done ?

**Pull request merged**
